### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/CheckLiveURLs#1]
- [ ] cocoapods?
- [ ] support GitHub repo
- [ ] let user enter repo
- [ ] mac app?
- [ ] crashes or errors when list of string urls is too big
- rebase 
- [ ] log when done
